tags:
- Genki_1
- Lesson_9
- Colors
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: くろい
    english: black
    kanji: 黒い
    kanji_readings:
    - 黒: くろ
    sound_file: genki_1/Kaiwa_Bunpo_L09/K09_07/K09_07_52.mp3
  - japanese: しろい
    english: white
    kanji: 白い
    kanji_readings:
    - 白: しろ
    sound_file: genki_1/Kaiwa_Bunpo_L09/K09_07/K09_07_54.mp3
  - japanese: あかい
    english: red
    kanji: 赤い
    kanji_readings:
    - 赤: あか
    sound_file: genki_1/Kaiwa_Bunpo_L09/K09_07/K09_07_50.mp3
  - japanese: あおい
    english: blue
    kanji: 青い
    kanji_readings:
    - 青: あお
    sound_file: genki_1/Kaiwa_Bunpo_L09/K09_07/K09_07_48.mp3
  - japanese: きいろい
    english: yellow
    kanji: 黄色い
    kanji_readings:
    - 黄色: きいろ
    sound_file: tts/きいろい_03aae.wav
  - japanese: ちゃいろい
    english: brown
    kanji: 茶色い
    kanji_readings:
    - 茶色: ちゃいろ
    sound_file: tts/ちゃいろい_77fdc.wav
  - japanese: みどり／グリーン
    english: green
    kanji: 緑
    kanji_readings:
    - 緑: みどり
    sound_file: tts/みどり／グリーン_a7a1e.wav
  - japanese: こんいろ
    english: navy blue
    kanji: 紺色
    kanji_readings:
    - 紺色: こんいろ
    sound_file: tts/こんいろ_aff56.wav
  - japanese: みずいろ
    english: light blue
    kanji: 水色
    kanji_readings:
    - 水色: みずいろ
    sound_file: tts/みずいろ_7a3fc.wav
  - japanese: ぎんいろ／シルバー
    english: silver
    kanji: 銀色
    kanji_readings:
    - 銀色: ぎんいろ
    sound_file: tts/ぎんいろ／シルバー_f4cf0.wav
  - japanese: オレンジ
    english: orange
    sound_file: tts/オレンジ_75e49.wav
  - japanese: むらさき
    english: purple
    kanji: 紫
    kanji_readings:
    - 紫: むらさき
    sound_file: tts/むらさき_701d7.wav
  - japanese: はいいろ／グレー
    english: gray
    kanji: 灰色
    kanji_readings:
    - 灰色: はいいろ
    sound_file: tts/はいいろ／グレー_5843e.wav
  - japanese: きんいろ／ゴールド
    english: gold
    kanji: 金色
    kanji_readings:
    - 金色: きんいろ
    sound_file: tts/きんいろ／ゴールド_f40de.wav
  - japanese: ピンク
    english: pink
    sound_file: tts/ピンク_547b8.wav
  - japanese: ベージュ
    english: beige
    sound_file: tts/ベージュ_2e6df.wav
  - japanese: かおがあおいですね。
    english: You look pale.
    kanji: 顔が青いですね。
    kanji_readings:
    - 顔: かお
    - 青: あお
    sound_file: tts/かおがあおいですね。_1af35.wav
  - japanese: しろくろのしゃしん
    english: black and white picture
    kanji: 白黒の写真
    kanji_readings:
    - 白黒: しろくろ
    - 写真: しゃしん
    sound_file: tts/しろくろのしゃしん_c8c7f.wav
  - japanese: あおしんごう
    english: green light
    kanji: 青信号
    kanji_readings:
    - 青: あお
    - 信号: しんごう
    sound_file: tts/あおしんごう_58e5d.wav
