tags:
- Genki_2
- Lesson_19
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: おくさま
    english: wife (polite)
    kanji: 奥様
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_3.mp3
  - japanese: おこさん
    english: child (polite)
    kanji: お子さん
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_5.mp3
  - japanese: ちゅうがくせい
    english: junior high school student
    kanji: 中学生
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_7.mp3
  - japanese: ぶちょう
    english: department manager
    kanji: 部長
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_9.mp3
  - japanese: しゅっちょう
    english: business trip
    kanji: 出張
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_11.mp3
  - japanese: けいご
    english: honorific language
    kanji: 敬語
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_13.mp3
  - japanese: こちら
    english: this way (polite)
    kanji: 此方（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_15.mp3
  - japanese: どちら
    english: where (polite)
    kanji: 何方（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_17.mp3
  - japanese: おれい
    english: expression of gratitude
    kanji: お礼
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_19.mp3
  - japanese: しゅるい
    english: a kind; a sort
    kanji: 種類
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_21.mp3
  - japanese: はなし
    english: talk; story
    kanji: 話
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_24.mp3
  - japanese: なやみ
    english: worry
    kanji: 悩み
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_27.mp3
  - japanese: まちがい
    english: mistake
    kanji: 間違い
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_29.mp3
  - japanese: せいかく
    english: personality
    kanji: 性格
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_31.mp3
  - japanese: なまけもの
    english: lazy person
    kanji: 怠け者
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_33.mp3
  - japanese: はずかしがりや
    english: shy person
    kanji: 恥ずかしがり屋
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_35.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: なかがいい
    english: be on good/close terms; to get along well
    kanji: 仲がいい
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_38.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: まじめ(な)
    english: serious; sober; diligent
    kanji: 真面目（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_43.mp3
- tags:
  - U_verbs
  vocabulary:
  - japanese: いらっしゃる
    english: honorific expression for いく、くる、and いる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_48.mp3
  - japanese: めしあがる
    english: honorific expression for たべる、のむ
    kanji: 召し上がる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_52.mp3
  - japanese: くださる
    english: honorific expression for くれる
    kanji: 下さる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_55.mp3
  - japanese: なさる
    english: honorific expression for する
    kanji: 為さる（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_57.mp3
  - japanese: おやすみになる
    english: honorific expression for ねる
    kanji: お休みになる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_59.mp3
  - japanese: ごらんになる
    english: honorific expression for みる
    kanji: ご覧になる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_61.mp3
  - japanese: おっしゃる
    english: honorific expression for いう
    kanji: 仰る（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_63.mp3
  - japanese: ～ていらっしゃる
    english: honorific expression for ～ている
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_65.mp3
  - japanese: おくる
    english: to walk/drive (someone) (personをplaceまで)
    kanji: 送る
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_67.mp3
  - japanese: おこる
    english: to get angry
    kanji: 怒る
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_70.mp3
  - japanese: きまる
    english: to be decided (～が)
    kanji: 決まる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_72.mp3
  - japanese: しりあう
    english: to get acquainted with (～と)
    kanji: 知り合う
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_74.mp3
  - japanese: よぶ
    english: to call (one's name) (～と); to invite (person を event に)
    kanji: 呼ぶ
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_76.mp3
  - japanese: ひっこす
    english: to move (to another place to live) (～に)
    kanji: 引っ越す
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_79.mp3
  - japanese: よる
    english: to stop by (place に)
    kanji: 寄る
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_81.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: おくれる
    english: to become late (～に)
    kanji: 遅れる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_84.mp3
  - japanese: かける
    english: to sit down (seat に)
    kanji: 掛ける（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_86.mp3
  - japanese: もてる
    english: to be popular (in terms of romantic interest) (people に)
    kanji: 持てる（rare、モテル also common）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_88.mp3
  - japanese: はれる
    english: to become sunny
    kanji: 晴れる
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_90.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: ごちそうする
    english: to treat/invite (someone) to a meal (person に meal を)
    kanji: ご馳走する（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_93.mp3
  - japanese: えんりょする
    english: to hold back for the time being; to refrain from
    kanji: 遠慮する
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_96.mp3
  - japanese: しょうたいする
    english: to invite someone (to an event/a place) (person を event に)
    kanji: 招待する
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_99.mp3
  - japanese: はなしをする
    english: to have a talk
    kanji: 話をする
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_101.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: おととい
    english: the day before yesterday
    kanji: 一昨日（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_104.mp3
  - japanese: まいあさ
    english: every morning
    kanji: 毎朝
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_106.mp3
  - japanese: それで
    english: then; therefore
    kanji: 其れで（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_108.mp3
  - japanese: なぜ
    english: why (=どうして)
    kanji: 何故（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_110.mp3
  - japanese: ほんとうは
    english: in fact; originally
    kanji: 本当は
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_112.mp3
  - japanese: まだ
    english: still
    kanji: 未だ（rare）
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_115.mp3
  - japanese: しょうしょう
    english: a few seconds
    kanji: 少々
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_117.mp3
  - japanese: ～めいさま
    english: a party of ... People
    kanji: ～名様
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_119.mp3
  - japanese: ようこそ
    english: welcome
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_122.mp3
  - japanese: よろしくおつたえください
    english: please give my best regards (to…) (～に)
    kanji: よろしくお伝えください
    sound_file: Kaiwa_Bunpo_L19/K19_07/K19_07_124.mp3
