tags:
- Genki_2
- Lesson_23
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: くつした
    english: socks
    kanji: 靴下
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_3.mp3
  - japanese: ふくろ
    english: sack; plastic/paper bag
    kanji: 袋
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_5.mp3
  - japanese: ただ
    english: free of charge
    kanji: 只（rare）
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_9.mp3
  - japanese: ゆうしょく
    english: dinner
    kanji: 夕食
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_11.mp3
  - japanese: ばしょ
    english: place
    kanji: 場所
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_13.mp3
  - japanese: かいだん
    english: stairs
    kanji: 階段
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_15.mp3
  - japanese: しょうがっこう
    english: elementary school
    kanji: 小学校
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_17.mp3
  - japanese: めんせつ
    english: interview
    kanji: 面接
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_19.mp3
  - japanese: けんこう
    english: health
    kanji: 健康
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_21.mp3
  - japanese: りそう
    english: ideal
    kanji: 理想
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_23.mp3
  - japanese: るすばん
    english: looking after a house during someone's absence
    kanji: 留守番
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_25.mp3
  - japanese: メッセージ
    english: message; text
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_27.mp3
  - japanese: きゅうこう
    english: class cancellation
    kanji: 休講
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_30.mp3
  - japanese: かいがいりょこう
    english: trip to a foreign country
    kanji: 海外旅行
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_32.mp3
  - japanese: ぼんおどり
    english: Bon dance (Japanese traditional dance)
    kanji: 盆踊り
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_34.mp3
  - japanese: おもいで
    english: memory
    kanji: 思い出
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_36.mp3
  - japanese: しゃかい
    english: society
    kanji: 社会
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_38.mp3
  - japanese: けっか
    english: result
    kanji: 結果
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_40.mp3
  - japanese: ちょうさ
    english: survey
    kanji: 調査
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_42.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: まずい
    english: (food is) terrible
    kanji: 不味い（rare）
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_45.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: かわいそう(な)
    english: pitiful; feel sorry for; poor thing
    kanji: 可哀相（rare）
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_48.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: あめがやむ
    english: the rain stops
    kanji: 雨が止む
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_53.mp3
  - japanese: ちがう
    english: to be different; to be wrong (～と)
    kanji: 違う
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_55.mp3
  - japanese: なくなる
    english: to be lost; to disappear (～が)
    kanji: 無くなる（rare）
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_58.mp3
  - japanese: いなくなる
    english: (someone) is gone; to disappear (～が)
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_61.mp3
  - japanese: おせわになる
    english: to be in someone's care (～に)
    kanji: お世話になる
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_64.mp3
  - japanese: おなかをこわす
    english: to have a stomache
    kanji: お腹を壊す（rare）
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_66.mp3
  - japanese: きにいる
    english: to find something agreeable (～が/を)
    kanji: 気に入る
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_68.mp3
  - japanese: わるぐちをいう
    english: to talk behind someone's back
    kanji: 悪口を言う
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_70.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: こたえる
    english: to answer (～に)
    kanji: 答える
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_73.mp3
  - japanese: はなれる
    english: (something/someone) separates; parts from (～と)
    kanji: 離れる
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_75.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: がっかりする
    english: to be disappointed (～に)
    kanji: ガッカリする（hiragana is more common）
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_79.mp3
  - japanese: がまんする
    english: to be tolerant/patient (～を)
    kanji: 我慢する
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_81.mp3
  - japanese: どうじょうする
    english: to sympathize (～に)
    kanji: 同情する
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_84.mp3
  - japanese: ～かおをする
    english: to look… (facial expression)
    kanji: ～顔をする
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_86.mp3
  - japanese: カンニングする
    english: to cheat in an exam
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_88.mp3
  - japanese: チェックする
    english: to check (～を)
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_90.mp3
  - japanese: せわをする
    english: to take care of…(～の)
    kanji: 世話をする
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_92.mp3
  - japanese: ゆうしょうする
    english: to win a championship
    kanji: 優勝する
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_94.mp3
  - japanese: もどってくる
    english: (something/someone) comes back
    kanji: 戻ってくる
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_96.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: そんな～
    english: such…; that kind of…
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_99.mp3
  - japanese: ～ために
    english: for…; for the sake of…
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_102.mp3
  - japanese: ものすごく
    english: extremely
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_105.mp3
  - japanese: そろそろ
    english: it is about time to...
    kanji: ソロソロ(hiragana is more common)
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_107.mp3
  - japanese: さいごに
    english: finally
    kanji: 最後に
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_109.mp3
  - japanese: げんきでね
    english: Take care of yourself.
    kanji: 元気でね
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_111.mp3
  - japanese: そうそう
    english: You are right.
    kanji: 然う然う（rare）
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_113.mp3
