tags:
- Genki_2
- Lesson_23
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: くつした
    english: socks
    kanji: 靴下
    kanji_readings:
    - 靴下: くつした
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_3.mp3
  - japanese: ふくろ
    english: sack; plastic/paper bag
    kanji: 袋
    kanji_readings:
    - 袋: ふくろ
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_5.mp3
  - japanese: ただ
    japanese_note: (rare)
    english: free of charge
    kanji: 只
    kanji_readings:
    - 只: ただ
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_9.mp3
  - japanese: ゆうしょく
    english: dinner
    kanji: 夕食
    kanji_readings:
    - 夕食: ゆうしょく
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_11.mp3
  - japanese: ばしょ
    english: place
    kanji: 場所
    kanji_readings:
    - 場所: ばしょ
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_13.mp3
  - japanese: かいだん
    english: stairs
    kanji: 階段
    kanji_readings:
    - 階段: かいだん
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_15.mp3
  - japanese: しょうがっこう
    english: elementary school
    kanji: 小学校
    kanji_readings:
    - 小: しょう
    - 学校: がっこう
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_17.mp3
  - japanese: めんせつ
    english: interview
    kanji: 面接
    kanji_readings:
    - 面接: めんせつ
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_19.mp3
  - japanese: けんこう
    english: health
    kanji: 健康
    kanji_readings:
    - 健康: けんこう
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_21.mp3
  - japanese: りそう
    english: ideal
    kanji: 理想
    kanji_readings:
    - 理想: りそう
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_23.mp3
  - japanese: るすばん
    english: looking after a house during someone's absence
    kanji: 留守番
    kanji_readings:
    - 留守: るす
    - 番: ばん
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_25.mp3
  - japanese: メッセージ
    english: message; text
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_27.mp3
  - japanese: きゅうこう
    english: class cancellation
    kanji: 休講
    kanji_readings:
    - 休講: きゅうこう
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_30.mp3
  - japanese: かいがいりょこう
    english: trip to a foreign country
    kanji: 海外旅行
    kanji_readings:
    - 海外: かいがい
    - 旅行: りょこう
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_32.mp3
  - japanese: ぼんおどり
    english: Bon dance (Japanese traditional dance)
    kanji: 盆踊り
    kanji_readings:
    - 盆踊: ぼんおど
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_34.mp3
  - japanese: おもいで
    english: memory
    kanji: 思い出
    kanji_readings:
    - 思い出: おもいで
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_36.mp3
  - japanese: しゃかい
    english: society
    kanji: 社会
    kanji_readings:
    - 社会: しゃかい
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_38.mp3
  - japanese: けっか
    english: result
    kanji: 結果
    kanji_readings:
    - 結果: けっか
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_40.mp3
  - japanese: ちょうさ
    english: survey
    kanji: 調査
    kanji_readings:
    - 調査: ちょうさ
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_42.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: まずい
    japanese_note: (rare)
    english: (food is) terrible
    kanji: 不味い
    kanji_readings:
    - 不味: まず
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_45.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: かわいそう(な)
    japanese_note: (rare)
    english: pitiful; feel sorry for; poor thing
    kanji: 可哀相
    kanji_readings:
    - 可哀相: かわいそう
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_48.mp3
- tags:
  - U-verbs
  - Verb
  vocabulary:
  - japanese: あめがやむ
    english: the rain stops
    kanji: 雨が止む
    kanji_readings:
    - 雨: あめ
    - 止: や
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_53.mp3
  - japanese: ちがう
    english: to be different; to be wrong (～と)
    kanji: 違う
    kanji_readings:
    - 違: ちが
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_55.mp3
  - japanese: なくなる
    japanese_note: (rare)
    english: to be lost; to disappear (～が)
    kanji: 無くなる
    kanji_readings:
    - 無: な
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_58.mp3
  - japanese: いなくなる
    english: (someone) is gone; to disappear (～が)
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_61.mp3
  - japanese: おせわになる
    english: to be in someone's care (～に)
    kanji: お世話になる
    kanji_readings:
    - 世話: せわ
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_64.mp3
  - japanese: おなかをこわす
    japanese_note: (rare)
    english: to have a stomache
    kanji: お腹を壊す
    kanji_readings:
    - 腹: なか
    - 壊: こわ
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_66.mp3
  - japanese: きにいる
    english: to find something agreeable (～が/を)
    kanji: 気に入る
    kanji_readings:
    - 気: き
    - 入: い
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_68.mp3
  - japanese: わるぐちをいう
    english: to talk behind someone's back
    kanji: 悪口を言う
    kanji_readings:
    - 悪口: わるぐち
    - 言: い
    verb_type: godan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_70.mp3
- tags:
  - Ru-verbs
  - Verb
  vocabulary:
  - japanese: こたえる
    english: to answer (～に)
    kanji: 答える
    kanji_readings:
    - 答: こた
    verb_type: ichidan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_73.mp3
  - japanese: はなれる
    english: (something/someone) separates; parts from (～と)
    kanji: 離れる
    kanji_readings:
    - 離: はな
    verb_type: ichidan
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_75.mp3
- tags:
  - Irregular_Verbs
  - Verb
  vocabulary:
  - japanese: がっかりする
    japanese_note: or ガッカリする (hiragana is more common)
    english: to be disappointed (～に)
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_79.mp3
  - japanese: がまんする
    english: to be tolerant/patient (～を)
    kanji: 我慢する
    kanji_readings:
    - 我慢: がまん
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_81.mp3
  - japanese: どうじょうする
    english: to sympathize (～に)
    kanji: 同情する
    kanji_readings:
    - 同情: どうじょう
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_84.mp3
  - japanese: ～かおをする
    english: to look… (facial expression)
    kanji: ～顔をする
    kanji_readings:
    - 顔: かお
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_86.mp3
  - japanese: カンニングする
    english: to cheat in an exam
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_88.mp3
  - japanese: チェックする
    english: to check (～を)
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_90.mp3
  - japanese: せわをする
    english: to take care of…(～の)
    kanji: 世話をする
    kanji_readings:
    - 世話: せわ
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_92.mp3
  - japanese: ゆうしょうする
    english: to win a championship
    kanji: 優勝する
    kanji_readings:
    - 優勝: ゆうしょう
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_94.mp3
  - japanese: もどってくる
    english: (something/someone) comes back
    kanji: 戻ってくる
    kanji_readings:
    - 戻: もど
    verb_type: irregular
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_96.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: そんな～
    english: such…; that kind of…
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_99.mp3
  - japanese: ～ために
    english: for…; for the sake of…
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_102.mp3
  - japanese: ものすごく
    english: extremely
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_105.mp3
  - japanese: そろそろ
    japanese_note: or ソロソロ (hiragana is more common)
    english: it is about time to...
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_107.mp3
  - japanese: さいごに
    english: finally
    kanji: 最後に
    kanji_readings:
    - 最後: さいご
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_109.mp3
  - japanese: げんきでね
    english: Take care of yourself.
    kanji: 元気でね
    kanji_readings:
    - 元気: げんき
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_111.mp3
  - japanese: そうそう
    japanese_note: (rare)
    english: You are right.
    kanji: 然う然う
    kanji_readings:
    - 然う然: そうそ
    sound_file: genki_2/Kaiwa_Bunpo_L23/K23_07/K23_07_113.mp3
