tags:
- Genki_1
- Lesson_12
- Health_And_Illness
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: げりです。
    english: I have diarrhea.
    kanji: 下痢です。
    kanji_readings:
    - 下痢: げり
    sound_file: tts/げりです。_0faf5.wav
  - japanese: べんぴです。
    english: I am constipated.
    kanji: 便秘です。
    kanji_readings:
    - 便秘: べんぴ
    sound_file: tts/べんぴです。_3bab4.wav
  - japanese: せいりです。
    english: I have my period.
    kanji: 生理です。
    kanji_readings:
    - 生理: せいり
    sound_file: tts/せいりです。_6864c.wav
  - japanese: かふんしょうです。
    english: I have hay fever.
    kanji: 花粉症です。
    kanji_readings:
    - 花粉: かふん
    - 症: しょう
    sound_file: tts/かふんしょうです。_bbe79.wav
  - japanese: （〜に）アレルギーがあります。
    english: I have an allergy to ...
    sound_file: tts/（〜に）アレルギーがあります。_f9b28.wav
  - japanese: むしばがあります。
    english: I have a bad tooth.
    kanji: 虫歯があります。
    kanji_readings:
    - 虫歯: むしば
    sound_file: tts/むしばがあります。_28545.wav
  - japanese: くしゃみがでます。
    english: I sneeze.
    kanji: くしゃみが出ます。
    kanji_readings:
    - 出: で
    sound_file: tts/くしゃみがでます。_23ae8.wav
  - japanese: はなみずがでます。
    english: I have a runny nose.
    kanji: 鼻水が出ます。
    kanji_readings:
    - 鼻水: はなみず
    - 出: で
    sound_file: tts/はなみずがでます。_6dce9.wav
  - japanese: せなかがかゆいです。
    english: My back itches.
    kanji: 背中がかゆいです。
    kanji_readings:
    - 背中: せなか
    sound_file: tts/せなかがかゆいです。_7ebcf.wav
  - japanese: はっしんがあります。
    english: I have rashes.
    kanji: 発疹があります。
    kanji_readings:
    - 発疹: はっしん
    sound_file: tts/はっしんがあります。_bc770.wav
  - japanese: めまいがします。
    english: I feel dizzy.
    sound_file: tts/めまいがします。_201c3.wav
  - japanese: はきました。
    english: I threw up.
    kanji: 吐きました。
    kanji_readings:
    - 吐: は
    sound_file: tts/はきました。_5786e.wav
  - japanese: きぶんがわるいです。
    english: I am not feeling well.
    kanji: 気分が悪いです。
    kanji_readings:
    - 気分: きぶん
    - 悪: わる
    sound_file: tts/きぶんがわるいです。_847f5.wav
  - japanese: やけどをしました。
    english: I burned myself.
    sound_file: tts/やけどをしました。_5d1d1.wav
  - japanese: あしをこっせつしました。
    english: I broke my leg.
    kanji: 足を骨折しました。
    kanji_readings:
    - 足: あし
    - 骨折: こっせつ
    sound_file: tts/あしをこっせつしました。_70287.wav
  - japanese: けがをしました。
    english: I hurt myself.
    sound_file: tts/けがをしました。_57c8f.wav
  - japanese: ないか
    english: physician
    kanji: 内科
    kanji_readings:
    - 内科: ないか
    sound_file: tts/ないか_8079c.wav
  - japanese: ひふか
    english: dermatologist
    kanji: 皮膚科
    kanji_readings:
    - 皮膚: ひふ
    - 科: か
    sound_file: tts/ひふか_a8eda.wav
  - japanese: げか
    english: surgeon
    kanji: 外科
    kanji_readings:
    - 外科: げか
    sound_file: tts/げか_9dd33.wav
  - japanese: さんふじんか
    english: obsterician and gynecologist
    kanji: 産婦人科
    kanji_readings:
    - 産: さん
    - 婦人: ふじん
    - 科: か
    sound_file: tts/さんふじんか_deee4.wav
  - japanese: せいけいげか
    english: orthopedic surgeon
    kanji: 整形外科
    kanji_readings:
    - 整形: せいけい
    - 外科: げか
    sound_file: tts/せいけいげか_6649e.wav
  - japanese: がんか（めいしゃ）
    english: ophthalmologist
    kanji: 眼科（目医者）
    kanji_readings:
    - 眼科: がんか
    - 目: め
    - 医者: いしゃ
    sound_file: tts/がんか（めいしゃ）_77b5c.wav
  - japanese: しか（はいしゃ）
    english: dentist
    kanji: 歯科（歯医者）
    kanji_readings:
    - 歯科: しか
    - 歯: は
    - 医者: いしゃ
    sound_file: tts/しか（はいしゃ）_ee0d7.wav
  - japanese: じびか
    english: otorhinolaryngologist; ENT doctor
    kanji: 耳鼻科
    kanji_readings:
    - 耳鼻: じび
    - 科: か
    sound_file: tts/じびか_5c4b3.wav
  - japanese: こうせいぶっしつ
    english: antibiotic
    kanji: 抗生物質
    kanji_readings:
    - 抗生: こうせい
    - 物質: ぶっしつ
    sound_file: tts/こうせいぶっしつ_f7815.wav
  - japanese: レントゲン
    english: X-ray
    sound_file: tts/レントゲン_0b64e.wav
  - japanese: しゅじゅつ
    english: operation
    kanji: 手術
    kanji_readings:
    - 手術: しゅじゅつ
    sound_file: tts/しゅじゅつ_edaed.wav
  - japanese: ちゅうしゃ
    english: injection
    kanji: 注射
    kanji_readings:
    - 注射: ちゅうしゃ
    sound_file: tts/ちゅうしゃ_2ed38.wav
  - japanese: たいおんけい
    english: thermometer
    kanji: 体温計
    kanji_readings:
    - 体温: たいおん
    - 計: けい
    sound_file: tts/たいおんけい_78ef2.wav
  - japanese: てんてき
    english: intravenous feeding
    kanji: 点滴
    kanji_readings:
    - 点滴: てんてき
    sound_file: tts/てんてき_50bfb.wav
