tags:
- Genki_1
- Lesson_2
- Grammar
vocabulary:
- tags:
  - Particles
  vocabulary:
  - japanese: XもY
    english: Also, too (X also Y)
  - japanese: Xね
    english: Isn't it? (X, right?)
  - japanese: Xよ
    english: I tell you (I'm telling you, X!)
- japanese: Xじゃないです
  english: Negative form of Xです (not X)
