tags:
- Genki_1
- Lesson_3
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - tags:
    - Entertainment_and_Sports
    vocabulary:
    - japanese: えいが
      english: movie
      kanji: 映画
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_4.mp3
    - japanese: おんがく
      english: music
      kanji: 音楽
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_6.mp3
    - japanese: ざっし
      english: magazine
      kanji: 雑誌
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_8.mp3
    - japanese: スポーツ
      english: sports
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_10.mp3
    - japanese: デート
      english: date (romantic, not calendar)
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_12.mp3
    - japanese: テニス
      english: tennis
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_14.mp3
    - japanese: テレビ
      english: TV
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_16.mp3
  - tags:
    - Foods_and_Drinks
    vocabulary:
    - japanese: アイスクリーム
      english: ice cream
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_19.mp3
    - japanese: ハンバーガー
      english: hamburger
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_21.mp3
    - japanese: おさけ
      english: sake; alcoholic drink
      kanji: お酒
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_23.mp3
    - japanese: おちゃ
      english: green tea
      kanji: お茶
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_26.mp3
    - japanese: コーヒー
      english: coffee
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_28.mp3
    - japanese: みず
      english: water
      kanji: 水
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_30.mp3
    - japanese: あさごはん
      english: breakfast
      kanji: 朝ご飯
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_32.mp3
    - japanese: ひるごはん
      english: lunch
      kanji: 昼ご飯
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_34.mp3
    - japanese: ばんごはん
      english: dinner
      kanji: 晩ご飯
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_36.mp3
  - tags:
    - Places
    vocabulary:
    - japanese: いえ
      english: home; house
      kanji: 家
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_39.mp3
    - japanese: うち
      english: home; house; my place
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_42.mp3
    - japanese: がっこう
      english: school
      kanji: 学校
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_46.mp3
    - japanese: カフェ
      english: cafe
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_48.mp3
  - tags:
    - Time
    vocabulary:
    - japanese: あした
      english: tomorrow
      kanji: 明日
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_51.mp3
    - japanese: きょう
      english: today
      kanji: 今日
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_53.mp3
    - japanese: あさ
      english: morning
      kanji: 朝
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_55.mp3
    - japanese: こんばん
      english: tonight
      kanji: 今晩
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_57.mp3
    - japanese: まいにち
      english: every day
      kanji: 毎日
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_59.mp3
    - japanese: まいばん
      english: every night
      kanji: 毎晩
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_61.mp3
    - japanese: しゅうまつ
      english: weekend
      kanji: 週末
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_63.mp3
    - japanese: どようび
      english: Saturday
      kanji: 土曜日
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_65.mp3
    - japanese: にちようび
      english: Sunday
      kanji: 日曜日
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_67.mp3
    - japanese: いつ
      english: when
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_69.mp3
    - japanese: 〜ごろ
      english: at about ...
      sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_71.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: いく
    english: to go (<i>destination</i> に/へ)
    kanji: 行く
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_74.mp3
  - japanese: かえる
    english: to go back; to return (<i>destination</i> に/へ)
    kanji: 帰る
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_76.mp3
  - japanese: きく
    english: to listen; to hear (〜を); to ask (<i>person</i>&nbsp;に)
    kanji: 聞く
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_79.mp3
  - japanese: のむ
    english: to drink (〜を)
    kanji: 飲む
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_82.mp3
  - japanese: はなす
    english: to speak; to talk (<i>language</i> を/で)
    kanji: 話す
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_84.mp3
  - japanese: よむ
    english: to read (〜を)
    kanji: 読む
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_87.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: おきる
    english: to get up
    kanji: 起きる
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_90.mp3
  - japanese: たべる
    english: to eat (〜を)
    kanji: 食べる
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_92.mp3
  - japanese: ねる
    english: to sleep; to go to sleep
    kanji: 寝る
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_94.mp3
  - japanese: みる
    english: to see; to look at; to watch (〜を)
    kanji: 見る
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_97.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: くる
    english: to come (<i>destination</i> に/へ)
    kanji: 来る
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_102.mp3
  - japanese: する
    english: to do (〜を)
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_104.mp3
  - japanese: べんきょうする
    english: to study (〜を)
    kanji: 勉強する
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_106.mp3
- tags:
  - Adjectives
  vocabulary:
  - japanese: いい
    english: good
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_109.mp3
  - japanese: はやい
    english: early
    kanji: 早い
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_111.mp3
- tags:
  - Adverbs
  vocabulary:
  - japanese: あまり + negative
    english: not much
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_114.mp3
  - japanese: ぜんぜん + negative
    english: not at all
    kanji: 全然
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_116.mp3
  - japanese: たいてい
    english: usually
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_118.mp3
  - japanese: ちょっと
    english: a little
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_120.mp3
  - japanese: ときどき
    english: sometimes
    kanji: 時々
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_122.mp3
  - japanese: よく
    english: often; much
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_124.mp3
- tags:
  - Expressions
  vocabulary:
  - japanese: そうですね
    english: That's right.; Let me see.
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_128.mp3
  - japanese: でも
    english: but
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_131.mp3
  - japanese: どうですか
    english: How about ...?; How is ...?
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_133.mp3
  - japanese: ええ
    english: yes (casual)
    sound_file: Kaiwa_Bunpo_L03/K03_05/K03_05_136.mp3
