tags:
- Genki_1
- Lesson_3
- Grammar
vocabulary:
- tags:
  - Particles
  vocabulary:
  - japanese: XをY
    japanese_note: (pronounced 'o')
    english: Direct object marker (Y verb operating on X)
    sound_file: tts/XをY_ff1d0.wav
  - japanese: XでY
    english: Location marker (At, in, on X, Y happens)
    sound_file: tts/XでY_735b6.wav
  - japanese: XにY
    english: Direction marker (To X, Y happens/At X time, Y happens)
    sound_file: tts/XにY_13ee3.wav
  - japanese: XへY
    japanese_note: (pronounced 'e')
    english: Direction marker (To X, Y happens)
    sound_file: tts/XへY_23d83.wav
- japanese: ～ませんか
  english: Invitation (Won't you do X?)
  sound_file: tts/～ませんか_7665c.wav
