tags:
- Genki_1
- Lesson_3
- Grammar
vocabulary:
- tags:
  - Particles
  vocabulary:
  - japanese: XをY
    japanese_note: (pronounced 'o')
    english: Direct object marker (Y verb operating on X)
    sound_file: tts/XをY_78de7.wav
  - japanese: XでY
    english: Location marker (At, in, on X, Y happens)
    sound_file: tts/XでY_91929.wav
  - japanese: XにY
    english: Direction marker (To X, Y happens/At X time, Y happens)
    sound_file: tts/XにY_f89ab.wav
  - japanese: XへY
    japanese_note: (pronounced 'e')
    english: Direction marker (To X, Y happens)
    sound_file: tts/XへY_f3246.wav
- japanese: ～ませんか
  english: Invitation (Won't you do X?)
  sound_file: tts/～ませんか_ea7c9.wav
