tags:
- Genki_1
- Lesson_5
- Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: たべもの
    english: food
    kanji: 食べ物
    kanji_readings:
    - 食べ物: たべもの
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_3.mp3
  - japanese: のみもの
    english: drink
    kanji: 飲み物
    kanji_readings:
    - 飲み物: のみもの
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_5.mp3
  - japanese: くだもの
    english: fruit
    kanji: 果物
    kanji_readings:
    - 果物: くだもの
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_7.mp3
  - japanese: やすみ
    english: holiday; day off; absence
    kanji: 休み
    kanji_readings:
    - 休: やす
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_9.mp3
  - japanese: りょこう
    english: travel
    kanji: 旅行
    kanji_readings:
    - 旅行: りょこう
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_13.mp3
  - japanese: うみ
    english: sea
    kanji: 海
    kanji_readings:
    - 海: うみ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_15.mp3
  - japanese: サーフィン
    english: surfing
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_17.mp3
  - japanese: おみやげ
    english: souvenir
    kanji: お土産
    kanji_readings:
    - 土産: みやげ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_19.mp3
  - japanese: バス
    english: bus
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_21.mp3
  - japanese: てんき
    english: weather
    kanji: 天気
    kanji_readings:
    - 天気: てんき
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_23.mp3
  - japanese: しゅくだい
    english: homework
    kanji: 宿題
    kanji_readings:
    - 宿題: しゅくだい
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_25.mp3
  - japanese: テスト
    english: test
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_27.mp3
  - japanese: たんじょうび
    english: birthday
    kanji: 誕生日
    kanji_readings:
    - 誕生: たんじょう
    - 日: び
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_29.mp3
  - japanese: へや
    english: room
    kanji: 部屋
    kanji_readings:
    - 部屋: へや
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_31.mp3
  - japanese: ぼく
    english: I (used by men)
    kanji: 僕
    kanji_readings:
    - 僕: ぼく
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_33.mp3
  - japanese: Lサイズ（エルサイズ）
    english: size L
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_35.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: あたらしい
    english: new
    kanji: 新しい
    kanji_readings:
    - 新: あたら
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_38.mp3
  - japanese: ふるい
    english: old (thing - not used for people)
    kanji: 古い
    kanji_readings:
    - 古: ふる
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_40.mp3
  - japanese: あつい
    japanese_note: weather / thing
    english: hot
    kanji: 暑い / 熱い
    kanji_readings:
    - 暑: あつ
    - 熱: あつ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_42.mp3
  - japanese: さむい
    english: cold (weather - not used for things)
    kanji: 寒い
    kanji_readings:
    - 寒: さむ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_44.mp3
  - japanese: いそがしい
    english: busy (people/days)
    kanji: 忙しい
    kanji_readings:
    - 忙: いそが
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_48.mp3
  - japanese: おおきい
    english: large
    kanji: 大きい
    kanji_readings:
    - 大: おお
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_50.mp3
  - japanese: ちいさい
    english: small
    kanji: 小さい
    kanji_readings:
    - 小: ちい
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_52.mp3
  - japanese: おもしろい
    english: interesting; funny
    kanji: 面白い
    kanji_readings:
    - 面白: おもしろ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_54.mp3
  - japanese: つまらない
    english: boring
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_57.mp3
  - japanese: やさしい
    english: easy (problem); kind (person)
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_59.mp3
  - japanese: むずかしい
    english: difficult
    kanji: 難しい
    kanji_readings:
    - 難: むずか
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_62.mp3
  - japanese: かっこいい
    english: good-looking (conjugates like いい)
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_64.mp3
  - japanese: こわい
    english: frightening
    kanji: 怖い
    kanji_readings:
    - 怖: こわ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_66.mp3
  - japanese: たのしい
    english: fun
    kanji: 楽しい
    kanji_readings:
    - 楽: たの
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_68.mp3
  - japanese: やすい
    english: inexpensive; cheap (thing)
    kanji: 安い
    kanji_readings:
    - 安: やす
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_70.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: すき（な）
    english: fond of; to like (〜が)
    kanji: 好き
    kanji_readings:
    - 好: す
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_74.mp3
  - japanese: きらい（な）
    english: disgusted with; to dislike (〜が)
    kanji: 嫌い
    kanji_readings:
    - 嫌: きら
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_77.mp3
  - japanese: だいすき（な）
    english: very fond of; to love (〜が)
    kanji: 大好き
    kanji_readings:
    - 大好: だいす
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_80.mp3
  - japanese: だいきらい（な）
    english: to hate (〜が)
    kanji: 大嫌い
    kanji_readings:
    - 大嫌: だいきら
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_83.mp3
  - japanese: きれい（な）
    english: beautiful; clean
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_85.mp3
  - japanese: げんき（な）
    english: healthy; energetic
    kanji: 元気
    kanji_readings:
    - 元気: げんき
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_88.mp3
  - japanese: しずか（な）
    english: quiet
    kanji: 静か
    kanji_readings:
    - 静: しず
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_91.mp3
  - japanese: にぎやか（な）
    english: lively
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_93.mp3
  - japanese: ひま（な）
    english: not busy; free (time)
    kanji: 暇
    kanji_readings:
    - 暇: ひま
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_95.mp3
- tags:
  - U-verbs
  - Verbs
  vocabulary:
  - japanese: およぐ
    english: to swim
    kanji: 泳ぐ
    kanji_readings:
    - 泳: およ
    verb_group: godan
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_99.mp3
  - japanese: きく
    english: to listen; to hear (〜を); to ask (<i>person</i>&nbsp;に)
    kanji: 聞く
    kanji_readings:
    - 聞: き
    verb_group: godan
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_101.mp3
  - japanese: のる
    english: to ride; to board (〜に)
    kanji: 乗る
    kanji_readings:
    - 乗: の
    verb_group: godan
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_103.mp3
  - japanese: やる
    english: to do; to perform (〜を)
    verb_group: godan
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_106.mp3
- tags:
  - Ru-verbs
  - Verbs
  vocabulary:
  - japanese: でかける
    english: to go out
    kanji: 出かける
    kanji_readings:
    - 出: で
    verb_group: ichidan
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_110.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: いっしょに
    english: together
    kanji: 一緒に
    kanji_readings:
    - 一緒: いっしょ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_113.mp3
  - japanese: すごく
    english: extremely
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_115.mp3
  - japanese: だいじょうぶ
    english: It's okay; Not to worry; Everything is under control.
    kanji: 大丈夫
    kanji_readings:
    - 大丈夫: だいじょうぶ
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_117.mp3
  - japanese: とても
    english: very
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_121.mp3
  - japanese: どんな
    english: what kind of ...
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_123.mp3
  - japanese: 〜まい
    english: '[counter for flat objects]'
    kanji: 〜枚
    kanji_readings:
    - 枚: まい
    sound_file: genki_1/Kaiwa_Bunpo_L05/K05_07/K05_07_125.mp3
