tags:
- Genki_2
- Lesson_13
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: おとな
    english: adult
    kanji: 大人
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_3.mp3
  - japanese: べんごし
    english: lawyer
    kanji: 弁護士
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_5.mp3
  - japanese: わたくし
    english: I (formal)
    kanji: 私
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_7.mp3
  - japanese: カレー
    english: curry
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_9.mp3
  - japanese: こうちゃ
    english: black tea
    kanji: 紅茶
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_11.mp3
  - japanese: きもの
    english: kimono; Japanese traditional dress
    kanji: 着物
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_13.mp3
  - japanese: セーター
    english: sweater
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_16.mp3
  - japanese: がっき
    english: musical instrument
    kanji: 楽器
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_18.mp3
  - japanese: からて
    english: karate
    kanji: 空手
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_20.mp3
  - japanese: ゴルフ
    english: golf
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_22.mp3
  - japanese: バイク
    english: motorcycle
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_24.mp3
  - japanese: ぞう
    english: elephant
    kanji: 象
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_26.mp3
  - japanese: からだ
    english: body
    kanji: 体
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_28.mp3
  - japanese: がいこくご
    english: foreign language
    kanji: 外国語
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_30.mp3
  - japanese: ことば
    english: language (words)
    kanji: 言葉
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_32.mp3
  - japanese: ぶんぽう
    english: grammar
    kanji: 文法
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_34.mp3
  - japanese: アプリ
    english: application
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_36.mp3
  - japanese: アパート
    english: apartment; smaller apartment building
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_38.mp3
  - japanese: マンション
    english: larger apartment building; condominium
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_41.mp3
  - japanese: くうこう
    english: airport
    kanji: 空港
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_44.mp3
  - japanese: みせ
    english: shop; store
    kanji: 店
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_46.mp3
  - japanese: ぶっか
    english: consumer prices
    kanji: 物価
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_49.mp3
  - japanese: こうこく
    english: advertisement
    kanji: 広告
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_51.mp3
  - japanese: ぼしゅう
    english: recruitment
    kanji: 募集
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_53.mp3
  - japanese: やくそく
    english: promise; appointment
    kanji: 約束
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_55.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: うれしい
    english: glad
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_58.mp3
  - japanese: かなしい
    english: sad
    kanji: 悲しい
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_60.mp3
  - japanese: きびしい
    english: strict
    kanji: 厳しい
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_62.mp3
  - japanese: きぶんがわるい
    english: to feel sick
    kanji: 気分が悪い
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_64.mp3
  - japanese: からい
    english: hot and spicy; salty
    kanji: 辛い
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_66.mp3
  - japanese: すごい
    english: incredible; awesome
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_69.mp3
  - japanese: ちかい
    english: close; near
    kanji: 近い
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_72.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: いろいろ(な)
    english: various; different kinds of
    kanji: 色々
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_76.mp3
  - japanese: しあわせ(な)
    english: happy (lasting happiness)
    kanji: 幸せ
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_79.mp3
  - japanese: だめ(な)
    english: no good
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_81.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: あむ
    english: to knit (~を)
    kanji: 編む
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_84.mp3
  - japanese: がんばる
    english: to do one's best; to try hard
    kanji: 頑張る
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_86.mp3
  - japanese: なく
    english: to cry
    kanji: 泣く
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_89.mp3
  - japanese: みがく
    english: to brush (teeth); to polish (~を)
    kanji: 磨く
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_91.mp3
  - japanese: やくそくをまもる
    english: to keep a promise (lit.”protect a promise”)
    kanji: 約束を守る
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_94.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: かんどうする
    english: to be moved; touched (by …) (~に)
    kanji: 感動する
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_97.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: 〜かい
    english: '...times'
    kanji: 〜回
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_101.mp3
  - japanese: 〜キロ
    english: '...kilometers; ...kilograms'
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_103.mp3
  - japanese: ぜんぶ
    english: all
    kanji: 全部
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_106.mp3
  - japanese: 〜ともうします
    english: my name is ~
    kanji: 〜と申します
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_108.mp3
  - japanese: とくに
    english: especially
    kanji: 特に
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_110.mp3
- tags:
  - Numbers
  vocabulary:
  - japanese: いちにち
    english: one day
    kanji: 一日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_113.mp3
  - japanese: ふつか
    english: two days
    kanji: 二日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_115.mp3
  - japanese: みっか
    english: three days
    kanji: 三日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_117.mp3
  - japanese: よっか
    english: four days
    kanji: 四日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_119.mp3
  - japanese: いつか
    english: five days
    kanji: 五日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_121.mp3
  - japanese: むいか
    english: six days
    kanji: 六日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_123.mp3
  - japanese: なのか
    english: seven days
    kanji: 七日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_125.mp3
  - japanese: ようか
    english: eight days
    kanji: 八日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_127.mp3
  - japanese: ここのか
    english: nine days
    kanji: 九日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_129.mp3
  - japanese: とおか
    english: ten days
    kanji: 十日
    sound_file: Kaiwa_Bunpo_L13/K13_07/K13_07_131.mp3
