tags:
- Genki_1
- Lesson_4
- Days_Month
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: ついたち*
    english: first day of the month
    kanji: 一日
    kanji_readings:
    - 一: つい
    - 日: たち
    sound_file: tts/ついたち_f9a5b.wav
    tts_override:
      text: ついたち
  - japanese: ふつか*
    english: second day of the month
    kanji: 二日
    kanji_readings:
    - 二: ふつ
    - 日: か
    sound_file: tts/ふつか_e1d6b.wav
  - japanese: みっか*
    english: third day of the month
    kanji: 三日
    kanji_readings:
    - 三: みっ
    - 日: か
    sound_file: tts/みっか_3621a.wav
  - japanese: よっか*
    english: fourth day of the month
    kanji: 四日
    kanji_readings:
    - 四: よっ
    - 日: か
    sound_file: tts/よっか_e06f3.wav
  - japanese: いつか*
    english: fifth day of the month
    kanji: 五日
    kanji_readings:
    - 五: いつ
    - 日: か
    sound_file: tts/いつか_86b4e.wav
  - japanese: むいか*
    english: sixth day of the month
    kanji: 六日
    kanji_readings:
    - 六: むい
    - 日: か
    sound_file: tts/むいか_21b35.wav
  - japanese: なのか*
    english: seventh day of the month
    kanji: 七日
    kanji_readings:
    - 七: なの
    - 日: か
    sound_file: tts/なのか_6cf98.wav
  - japanese: ようか*
    english: eighth day of the month
    kanji: 八日
    kanji_readings:
    - 八: よう
    - 日: か
    sound_file: tts/ようか_80d7e.wav
  - japanese: ここのか*
    english: ninth day of the month
    kanji: 九日
    kanji_readings:
    - 九: ここの
    - 日: か
    sound_file: tts/ここのか_57cb7.wav
  - japanese: とおか*
    english: tenth day of the month
    kanji: 十日
    kanji_readings:
    - 十: とお
    - 日: か
    sound_file: tts/とおか_6f8df.wav
  - japanese: じゅういちにち
    english: eleventh day of the month
    kanji: 十一日
    kanji_readings:
    - 十: じゅう
    - 一: いち
    - 日: にち
    sound_file: tts/じゅういちにち_4ac3b.wav
  - japanese: じゅうににち
    english: twelfth day of the month
    kanji: 十二日
    kanji_readings:
    - 十: じゅう
    - 二: に
    - 日: にち
    sound_file: tts/じゅうににち_5b7f8.wav
  - japanese: じゅうさんにち
    english: thirteenth day of the month
    kanji: 十三日
    kanji_readings:
    - 十: じゅう
    - 三: さん
    - 日: にち
    sound_file: tts/じゅうさんにち_62b6d.wav
  - japanese: じゅうよっか*
    english: fourteenth day of the month
    kanji: 十四日
    kanji_readings:
    - 十: じゅう
    - 四: よっ
    - 日: か
    sound_file: tts/じゅうよっか_a8978.wav
  - japanese: じゅうごにち
    english: fifteenth day of the month
    kanji: 十五日
    kanji_readings:
    - 十: じゅう
    - 五: ご
    - 日: にち
    sound_file: tts/じゅうごにち_d3bd9.wav
  - japanese: 〜にち
    english: day ...
    kanji: 〜日
    kanji_readings:
    - 日: にち
    sound_file: tts/〜にち_5e6a8.wav
  - japanese: はつか*
    english: twentieth day of the month
    kanji: 二十日・廿日
    kanji_readings:
    - 二十: はつ
    - 日: か
    - 廿: はつ
    - 日: か
    sound_file: tts/はつか_fcaf5.wav
  - japanese: にじゅうよっか*
    english: twenty-fourth day of the month
    kanji: 二十四日
    kanji_readings:
    - 二十: にじゅう
    - 四: よっ
    - 日: か
    sound_file: tts/にじゅうよっか_55492.wav
