tags:
- Genki_1
- Lesson_4
- Months
vocabulary:
- japanese: いちがつ
  english: January
  kanji: 一月
  kanji_readings:
  - 一: いち
  - 月: がつ
  sound_file: tts/いちがつ_993e5.wav
- japanese: にがつ
  english: February
  kanji: 二月
  kanji_readings:
  - 二: に
  - 月: がつ
  sound_file: tts/にがつ_92f0e.wav
- japanese: さんがつ
  english: March
  kanji: 三月
  kanji_readings:
  - 三: さん
  - 月: がつ
  sound_file: tts/さんがつ_be152.wav
- japanese: しがつ*
  english: April
  kanji: 四月
  kanji_readings:
  - 四: し
  - 月: がつ
  sound_file: tts/しがつ_0404a.wav
- japanese: ごがつ
  english: May
  kanji: 五月
  kanji_readings:
  - 五: ご
  - 月: がつ
  sound_file: tts/ごがつ_2a737.wav
- japanese: ろくがつ
  english: June
  kanji: 六月
  kanji_readings:
  - 六: ろく
  - 月: がつ
  sound_file: tts/ろくがつ_5d575.wav
- japanese: しちがつ*
  english: July
  kanji: 七月
  kanji_readings:
  - 七: しち
  - 月: がつ
  sound_file: tts/しちがつ_5c8e3.wav
- japanese: はちがつ
  english: August
  kanji: 八月
  kanji_readings:
  - 八: はち
  - 月: がつ
  sound_file: tts/はちがつ_20cbd.wav
- japanese: くがつ*
  english: September
  kanji: 九月
  kanji_readings:
  - 九: く
  - 月: がつ
  sound_file: tts/くがつ_256ad.wav
- japanese: じゅうがつ
  english: October
  kanji: 十月
  kanji_readings:
  - 十: じゅう
  - 月: がつ
  sound_file: tts/じゅうがつ_280ec.wav
- japanese: じゅういちがつ
  english: November
  kanji: 十一月
  kanji_readings:
  - 十: じゅう
  - 一: いち
  - 月: がつ
  sound_file: tts/じゅういちがつ_a5fba.wav
- japanese: じゅうにがつ
  english: December
  kanji: 十二月
  kanji_readings:
  - 十: じゅう
  - 二: に
  - 月: がつ
  sound_file: tts/じゅうにがつ_60ca7.wav
