tags:
- Genki_1
- Lesson_3
- Grammar
vocabulary:
- tags:
  - Particles
  vocabulary:
  - japanese: XがY
    english: Subject marker (Regarding X, Y)
  - japanese: XとY
    english: And (X and Y), with (Y with X)
