tags:
- Genki_1
- Lesson_10
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: きせつ
    english: season
    kanji: 季節
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_3.mp3
  - japanese: はる
    english: spring
    kanji: 春
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_5.mp3
  - japanese: あき
    english: fall
    kanji: 秋
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_7.mp3
  - japanese: ぎゅうにゅう
    english: milk
    kanji: 牛乳
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_9.mp3
  - japanese: ケーキ
    english: cake
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_11.mp3
  - japanese: すし
    english: sushi
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_13.mp3
  - japanese: てんぷら
    english: tempura
    kanji: 天ぷら
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_15.mp3
  - japanese: りんご
    english: apple
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_17.mp3
  - japanese: りょうり
    english: cuisine
    kanji: 料理
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_19.mp3
  - japanese: サッカー
    english: soccer
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_21.mp3
  - japanese: やきゅう
    english: baseball
    kanji: 野球
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_23.mp3
  - japanese: いしゃ
    english: doctor
    kanji: 医者
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_25.mp3
  - japanese: おかねもち
    english: rich person
    kanji: お金持ち
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_27.mp3
  - japanese: ゆうめいじん
    english: celebrity
    kanji: 有名人
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_29.mp3
  - japanese: かお
    english: face
    kanji: 顔
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_31.mp3
  - japanese: としうえ
    english: someone older
    kanji: 年上
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_33.mp3
  - japanese: えき
    english: station
    kanji: 駅
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_35.mp3
  - japanese: しんかんせん
    english: Shinkansen; "Bullet Train"
    kanji: 新幹線
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_37.mp3
  - japanese: ちかてつ
    english: subway
    kanji: 地下鉄
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_40.mp3
  - japanese: ふね
    english: ship; boat
    kanji: 船
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_42.mp3
  - japanese: ひこうき
    english: airplane
    kanji: 飛行機
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_45.mp3
  - japanese: よやく
    english: reservation
    kanji: 予約
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_47.mp3
  - japanese: ツアー
    english: tour
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_49.mp3
  - japanese: どうぶつえん
    english: zoo
    kanji: 動物園
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_51.mp3
  - japanese: じかん
    english: time
    kanji: 時間
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_53.mp3
  - japanese: せかい
    english: world
    kanji: 世界
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_55.mp3
  - japanese: びよういん
    english: beauty parlor
    kanji: 美容院
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_57.mp3
  - japanese: てぶくろ
    english: gloves
    kanji: 手袋
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_59.mp3
  - japanese: せいかつ
    english: life; living
    kanji: 生活
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_61.mp3
  - japanese: ことし
    english: this year
    kanji: 今年
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_64.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: あたたかい
    english: warm
    kanji: 暖かい
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_67.mp3
  - japanese: すずしい
    english: cool (weather - not used for things)
    kanji: 涼しい
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_69.mp3
  - japanese: つめたい
    english: cold (things/people)
    kanji: 冷たい
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_71.mp3
  - japanese: おそい
    english: slow; late
    kanji: 遅い
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_73.mp3
  - japanese: ねむい
    english: sleepy
    kanji: 眠い
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_76.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: かんたん（な）
    english: easy; simple
    kanji: 簡単
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_79.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: かかる
    english: to take (amount of time/money) (<i>no particle</i>)
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_83.mp3
  - japanese: とまる
    english: to stay (at a hotel, etc.) (〜に)
    kanji: 泊まる
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_86.mp3
  - japanese: なる
    english: to become
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_88.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: きめる
    english: to decide (〜を)
    kanji: 決める
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_91.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: ごろごろする
    english: to chill out at home; to stay home and do nothing
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_94.mp3
  - japanese: りょこうする
    english: to travel
    kanji: 旅行する
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_97.mp3
  - japanese: れんしゅうする
    english: to practice (〜を)
    kanji: 練習する
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_99.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: いちばん
    english: best
    kanji: 一番
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_102.mp3
  - japanese: どっち／どちら
    english: which
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_104.mp3
  - japanese: はやく
    english: (do something) early; fast
    kanji: 早く／速く
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_107.mp3
  - japanese: あるいて
    english: on foot
    kanji: 歩いて
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_110.mp3
  - japanese: 〜で
    english: by (means of transportation); with (a tool)
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_112.mp3
  - japanese: どうやって
    english: how; by what means
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_115.mp3
  - japanese: どのぐらい
    english: how much; how long
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_118.mp3
  - japanese: 〜しゅうかん
    english: for ... weeks
    kanji: 〜週間
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_121.mp3
  - japanese: 〜かげつ
    english: for ... months
    kanji: 〜か月
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_124.mp3
  - japanese: 〜ねん
    english: '... years'
    kanji: 〜年
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_127.mp3
  - japanese: このごろ
    english: these days
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_129.mp3
  - japanese: 〜ご
    english: in ... time; after ...
    kanji: 〜後
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_131.mp3
  - japanese: 〜か〜
    english: or
    sound_file: genki_1/Kaiwa_Bunpo_L10/K10_05/K10_05_134.mp3
