tags:
- Genki_1
- Lesson_6
- 02_Useful_Expressions
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: ひだりにまがる
    english: turn left
    kanji: 左に曲がる
    sound_file: tts/ひだりにまがる_4d2fb.wav
  - japanese: みぎにまがる
    english: turn right
    kanji: 右に曲がる
    sound_file: tts/みぎにまがる_0e863.wav
  - japanese: まっすぐいく
    english: go straight
    kanji: まっすぐ行く
    sound_file: tts/まっすぐいく_5b7de.wav
  - japanese: みちをわたる
    english: cross the street
    kanji: 道を渡る
    sound_file: tts/みちをわたる_23f4d.wav
  - japanese: ふたつめのかどをひだりにまがる
    english: turn left at the second corner
    kanji: ニつ目の角を左に曲がる
    sound_file: tts/ふたつめのかどをひだりにまがる_8f42d.wav
  - japanese: ひとつめのしんごうをみぎにまがる
    english: turn right at the first traffic light
    kanji: 一つ目の信号を右に曲がる
    sound_file: tts/ひとつめのしんごうをみぎにまがる_0aeec.wav
  - japanese: みちのひだりがわ
    english: left side of the street
    kanji: 道の左側
    sound_file: tts/みちのひだりがわ_54118.wav
  - japanese: みちのみぎがわ
    english: right side of the street
    kanji: 道の右側
    sound_file: tts/みちのみぎがわ_62b56.wav
  - japanese: きた
    english: north
    kanji: 北
    sound_file: tts/きた_db3dc.wav
  - japanese: にし
    english: west
    kanji: 西
    sound_file: tts/にし_2321d.wav
  - japanese: ひがし
    english: east
    kanji: 東
    sound_file: tts/ひがし_6101d.wav
  - japanese: みなみ
    english: south
    kanji: 南
    sound_file: tts/みなみ_cdbe7.wav
