tags:
- Genki_2
- Lesson_14
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: おくさん
    english: wife (honorific)
    kanji: 奥さん
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_3.mp3
  - japanese: ごしゅじん
    english: husband (honorific)
    kanji: ご主人
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_5.mp3
  - japanese: パートナー
    english: partner
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_7.mp3
  - japanese: おじさん
    english: uncle; middle-aged man
    kanji: 伯父さん(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_9.mp3
  - japanese: おばさん
    english: aunt; middle-aged woman
    kanji: 伯母さん(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_12.mp3
  - japanese: りょうしん
    english: parents
    kanji: 両親
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_15.mp3
  - japanese: おおやさん
    english: landlord; landlady
    kanji: 大家さん
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_17.mp3
  - japanese: みなさん
    english: everyone; all of you
    kanji: 皆さん
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_20.mp3
  - japanese: チョコレート
    english: chocolate
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_23.mp3
  - japanese: みかん
    english: mandarin orange
    kanji: 蜜柑(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_25.mp3
  - japanese: トレーナー
    english: sweatshirt
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_27.mp3
  - japanese: シャツ
    english: shirt
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_29.mp3
  - japanese: ネクタイ
    english: necktie
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_31.mp3
  - japanese: マフラー
    english: winter scarf
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_33.mp3
  - japanese: ゆびわ
    english: ring
    kanji: 指輪
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_35.mp3
  - japanese: えんぴつ
    english: pencil
    kanji: 鉛筆
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_37.mp3
  - japanese: ぬいぐるみ
    english: stuffed animal (e.g. teddy bear)
    kanji: 縫いぐるみ(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_39.mp3
  - japanese: まんが
    english: comic book
    kanji: 漫画
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_41.mp3
  - japanese: けしょうひん
    english: cosmetics
    kanji: 化粧品
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_43.mp3
  - japanese: ラジオ
    english: radio
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_45.mp3
  - japanese: おさら
    english: plate; dish
    kanji: お皿
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_47.mp3
  - japanese: おかえし
    english: return (as a token of gratitude)
    kanji: お返し
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_50.mp3
  - japanese: りれきしょ
    english: resume/cv
    kanji: 履歴書
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_52.mp3
  - japanese: クリスマス
    english: Christmas
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_54.mp3
  - japanese: バレンタインデー
    english: Valentine's Day
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_56.mp3
  - japanese: ホワイトデー
    english: White Day
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_58.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: ほしい
    english: to want (desired thing が)
    kanji: 欲しい
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_61.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: おしゃれ(な)
    english: fashionable; stylish
    kanji: お洒落
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_64.mp3
  - japanese: けち(な)
    english: stingy; cheap
    kanji: ケチ(hiragana is also common)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_67.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: おくる
    english: to send
    kanji: 送る
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_71.mp3
  - japanese: にあう
    english: to look good on somebody (thing が）
    kanji: 似合う
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_73.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: あきらめる
    english: to give up (~を)
    kanji: 諦める
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_76.mp3
  - japanese: あげる
    english: to give (to others) (person に thing を)
    kanji: 上げる(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_78.mp3
  - japanese: くれる
    english: To give (to me) (person に thing を)
    kanji: 呉れる(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_80.mp3
  - japanese: できる
    english: to come into existence; to be made (~が)
    kanji: 出来る (rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_82.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: そうだんする
    english: to consult (person に）
    kanji: 相談する
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_86.mp3
  - japanese: ちゅういする
    english: To give warning (person に); to watch out (~に)
    kanji: 注意する
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_88.mp3
  - japanese: プロポーズする
    english: to propose marriage (person に)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_91.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: 〜くん
    english: Mr;Ms. (casual)
    kanji: 〜君
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_94.mp3
  - japanese: 〜たち
    english: make a noun plural
    kanji: 〜達(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_97.mp3
  - japanese: わたしたち
    english: we/us
    kanji: 私達(私たちis common)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_99.mp3
  - japanese: こんな~
    english: '...like this; this kind of…'
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_101.mp3
  - japanese: きゅうに
    english: suddenly
    kanji: 急に
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_104.mp3
  - japanese: ちょうど
    english: exactly
    kanji: 丁度 (rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_106.mp3
  - japanese: よく
    english: well
    kanji: 良く(rare)
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_108.mp3
  - japanese: さあ
    english: I am not sure…
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_110.mp3
  - japanese: どうしたらいい
    english: what should one do
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_112.mp3
- tags:
  - Counters
  vocabulary:
  - japanese: 〜こ
    english: generic counter for smaller items
    kanji: 〜個
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_115.mp3
  - japanese: 〜さつ
    english: counter for bound volumes
    kanji: 〜冊
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_117.mp3
  - japanese: 〜だい
    english: counter for equipment
    kanji: 〜台
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_119.mp3
  - japanese: 〜ひき
    english: counter for smaller animals
    kanji: 〜匹
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_121.mp3
  - japanese: 〜ほん
    english: counter for long objects
    kanji: 〜本
    sound_file: genki_2/Kaiwa_Bunpo_L14/K14_07/K14_07_123.mp3
