tags:
- Genki_1
- Lesson_1
- 01_Vocabulary
vocabulary:
- tags:
  - School
  vocabulary:
  - japanese: だいがく
    english: college; university
    kanji: 大学
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_3.mp3
  - japanese: こうこう
    english: high school
    kanji: 高校
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_5.mp3
  - japanese: がくせい
    english: student
    kanji: 学生
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_7.mp3
  - japanese: だいがくせい
    english: college student
    kanji: 大学生
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_9.mp3
  - japanese: りゅうがくせい
    english: international student
    kanji: 留学生
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_11.mp3
  - japanese: せんせい
    english: teacher; Professor ...
    kanji: 先生
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_13.mp3
  - japanese: 〜ねんせい
    english: '... year student'
    kanji: 〜年生
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_15.mp3
  - japanese: いちねんせい
    english: first-year student
    kanji: 一年生
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_17.mp3
  - japanese: せんこう
    english: major
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_19.mp3
- tags:
  - Person
  vocabulary:
  - japanese: わたし
    english: I
    kanji: 私
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_22.mp3
  - japanese: ともだち
    english: friend
    kanji: 友達
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_24.mp3
  - japanese: 〜さん
    english: Mr./Ms. ...
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_26.mp3
  - japanese: 〜じん
    english: '... people'
    kanji: 人
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_28.mp3
  - japanese: にほんじん
    english: Japanese people
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_30.mp3
- tags:
  - Time
  vocabulary:
  - japanese: いま
    english: now
    kanji: 今
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_33.mp3
  - japanese: ごぜん
    english: A.M.
    kanji: 午前
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_35.mp3
  - japanese: ごご
    english: P.M.
    kanji: 午後
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_37.mp3
  - japanese: 〜じ
    english: o'clock
    kanji: 時
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_39.mp3
  - japanese: いちじ
    english: 1 o'clock
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_41.mp3
  - japanese: はん
    english: half
    kanji: 半
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_43.mp3
  - japanese: にじはん
    english: half past two
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_45.mp3
- tags:
  - Others
  vocabulary:
  - japanese: にほん
    english: Japan
    kanji: 日本
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_48.mp3
  - japanese: アメリカ
    english: U.S.A.
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_50.mp3
  - japanese: 〜ご
    english: '... language'
    kanji: 語
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_52.mp3
  - japanese: にほんご
    english: Japanese language
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_54.mp3
  - japanese: 〜さい
    english: '... years old'
    kanji: 歳
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_56.mp3
  - japanese: でんわ
    english: telephone
    kanji: 電話
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_58.mp3
  - japanese: 〜ばん
    english: number ...
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_60.mp3
  - japanese: ばんごう
    english: number
    kanji: 番号
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_62.mp3
  - japanese: なまえ
    english: name
    kanji: 名前
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_64.mp3
  - japanese: なん／なに
    english: what
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_66.mp3
- tags:
  - Expressions
  vocabulary:
  - japanese: あのう
    english: um ...
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_69.mp3
  - japanese: はい
    english: yes (formal)
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_71.mp3
  - japanese: そうです
    english: That's right.
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_73.mp3
  - japanese: そうですか。
    english: I see.
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_75.mp3
  - japanese: そうですか？
    english: Is that so?
    sound_file: Kaiwa_Bunpo_L01/K01_05/K01_05_77.mp3
