tags:
- Genki_1
- Lesson_1
- Additional_Vocabulary
vocabulary:
- tags:
  - Countries
  vocabulary:
  - japanese: イギリス
    english: Britain
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_2.mp3
  - japanese: オーストラリア
    english: Australia
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_4.mp3
  - japanese: かんこく
    english: Korea
    kanji: 韓国
    kanji_readings:
    - 韓国: かんこく
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_6.mp3
  - japanese: カナダ
    english: Canada
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_8.mp3
  - japanese: ちゅうごく
    english: China
    kanji: 中国
    kanji_readings:
    - 中国: ちゅうごく
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_10.mp3
  - japanese: インド
    english: India
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_12.mp3
  - japanese: エジプト
    english: Egypt
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_14.mp3
  - japanese: フィリピン
    english: Philippines
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_16.mp3
- tags:
  - Majors
  vocabulary:
  - japanese: アジアけんきゅう
    english: Asian studies
    kanji: アジア研究
    kanji_readings:
    - 研究: けんきゅう
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_19.mp3
  - japanese: けいざい
    english: economics
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_21.mp3
  - japanese: こうがく
    english: engineering
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_23.mp3
  - japanese: こくさいかんけい
    english: international relations
    kanji: 国際関係
    kanji_readings:
    - 国際: こくさい
    - 関係: かんけい
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_25.mp3
  - japanese: コンピューター
    english: computer
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_27.mp3
  - japanese: せいじ
    english: politics
    kanji: 政治
    kanji_readings:
    - 政治: せいじ
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_29.mp3
  - japanese: せいぶつがく
    english: biology
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_31.mp3
  - japanese: ビジネス
    english: business
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_33.mp3
  - japanese: ぶんがく
    english: literature
    kanji: 文学
    kanji_readings:
    - 文学: ぶんがく
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_35.mp3
  - japanese: れきし
    english: history
    kanji: 歴史
    kanji_readings:
    - 歴史: れきし
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_37.mp3
- tags:
  - Occupations
  vocabulary:
  - japanese: いしゃ
    english: doctor
    kanji: 医者
    kanji_readings:
    - 医者: いしゃ
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_40.mp3
  - japanese: かいしゃいん
    english: office worker
    kanji: 会社員
    kanji_readings:
    - 会社: かいしゃ
    - 員: いん
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_42.mp3
  - japanese: かんごし
    english: nurse
    kanji: 看護師
    kanji_readings:
    - 看護: かんご
    - 師: し
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_44.mp3
  - japanese: こうこうせい
    english: high school student
    kanji: 高校生
    kanji_readings:
    - 高校: こうこう
    - 生: せい
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_46.mp3
  - japanese: しゅふ
    english: housewife
    kanji: 主婦
    kanji_readings:
    - 主婦: しゅふ
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_48.mp3
  - japanese: だいがくいんせい
    english: graduate student
    kanji: 大学院生
    kanji_readings:
    - 大学: だいがく
    - 院: いん
    - 生: せい
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_50.mp3
  - japanese: べんごし
    english: lawyer
    kanji: 弁護士
    kanji_readings:
    - 弁護: べんご
    - 士: し
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_52.mp3
- tags:
  - Family
  vocabulary:
  - japanese: おかあさん
    english: mother
    kanji: お母さん
    kanji_readings:
    - 母: かあ
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_55.mp3
  - japanese: おとうさん
    english: father
    kanji: お父さん
    kanji_readings:
    - 父: とう
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_57.mp3
  - japanese: おねえさん
    english: older sister
    kanji: お姉さん
    kanji_readings:
    - 姉: ねえ
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_59.mp3
  - japanese: おにいさん
    english: older brother
    kanji: お兄さん
    kanji_readings:
    - 兄: にい
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_61.mp3
  - japanese: いもうと
    english: younger sister
    kanji: 妹
    kanji_readings:
    - 妹: いもうと
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_63.mp3
  - japanese: おとうと
    english: younger brother
    kanji: 弟
    kanji_readings:
    - 弟: おとうと
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_07/K01_07_65.mp3
