tags:
- Genki_1
- Lesson_1
- Year_Student
vocabulary:
- japanese: いちねんせい
  english: first-year student
  kanji: 一年生
  kanji_readings:
  - 一: いち
  - 年: ねん
  - 生: せい
  sound_file: genki_1/Kaiwa_Bunpo_L01/K01_05/K01_05_17.mp3
- japanese: にねんせい
  english: second-year student
  kanji: 二年生
  kanji_readings:
  - 二: に
  - 年: ねん
  - 生: せい
  sound_file: tts/にねんせい_3f9e5.wav
- japanese: さんねんせい
  english: third-year student
  kanji: 三年生
  kanji_readings:
  - 三: さん
  - 年: ねん
  - 生: せい
  sound_file: tts/さんねんせい_b7bca.wav
- japanese: よねんせい*
  english: fourth-year student
  kanji: 四年生
  kanji_readings:
  - 四: よん
  - 年: ねん
  - 生: せい
  sound_file: tts/よねんせい_6512f.wav
- japanese: ごねんせい
  english: fifth-year student
  kanji: 五年生
  kanji_readings:
  - 五: ご
  - 年: ねん
  - 生: せい
  sound_file: tts/ごねんせい_a64d9.wav
- japanese: ろくねんせい
  english: sixth-year student
  kanji: 六年生
  kanji_readings:
  - 六: ろく
  - 年: ねん
  - 生: せい
  sound_file: tts/ろくねんせい_8fdda.wav
