tags:
- Genki_1
- Lesson_1
- 05_Hours
vocabulary:
- tags:
  - hours
  vocabulary:
  - japanese: いちじ
    english: 1 o'clock
    kanji: 一時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_2.mp3
  - japanese: にじ
    english: 2 o'clock
    kanji: 二時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_3.mp3
  - japanese: さんじ
    english: 3 o'clock
    kanji: 三時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_4.mp3
  - japanese: よじ*
    english: 4 o'clock
    kanji: 四時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_5.mp3
  - japanese: ごじ
    english: 5 o'clock
    kanji: 五時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_6.mp3
  - japanese: ろくじ
    english: 6 o'clock
    kanji: 六時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_7.mp3
  - japanese: しちじ*
    english: 7 o'clock
    kanji: 七時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_8.mp3
  - japanese: はちじ
    english: 8 o'clock
    kanji: 八時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_9.mp3
  - japanese: くじ*
    english: 9 o'clock
    kanji: 九時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_10.mp3
  - japanese: じゅうじ
    english: 10 o'clock
    kanji: 十時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_11.mp3
  - japanese: じゅういちじ
    english: 11 o'clock
    kanji: 十一時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_12.mp3
  - japanese: じゅうにじ
    english: 12 o'clock
    kanji: 十二時
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_13.mp3
  - japanese: いちじはん
    english: '1:30'
    kanji: 一時半
    sound_file: genki_1/Kaiwa_Bunpo_L01/K01_21/K01_21_14.mp3
