tags:
- Genki_1
- Lesson_1
- 06_Minutes
vocabulary:
- tags:
  - minutes
  vocabulary:
  - japanese: いっぷん*
    english: 1 minute
    kanji: 一分
    sound_file: tts/いっぷん_d248b.wav
  - japanese: にふん
    english: 2 minutes
    kanji: 二分
    sound_file: tts/にふん_56ee6.wav
  - japanese: さんぷん*
    english: 3 minutes
    kanji: 三分
    sound_file: tts/さんぷん_3ef14.wav
  - japanese: よんぷん*
    english: 4 minutes
    kanji: 四分
    sound_file: tts/よんぷん_33e35.wav
  - japanese: ごふん
    english: 5 minutes
    kanji: 五分
    sound_file: tts/ごふん_41243.wav
  - japanese: ろっぷん*
    english: 6 minutes
    kanji: 六分
    sound_file: tts/ろっぷん_e9f1b.wav
  - japanese: ななふん
    english: 7 minutes
    kanji: 七分
    sound_file: tts/ななふん_d9a53.wav
  - japanese: はっぷん*
    english: 8 minutes
    kanji: 八分
    sound_file: tts/はっぷん_d0370.wav
  - japanese: きゅうふん
    english: 9 minutes
    kanji: 九分
    sound_file: tts/きゅうふん_2d176.wav
  - japanese: じゅっぷん*
    english: 10 minutes
    kanji: 十分
    sound_file: tts/じゅっぷん_4bebd.wav
  - japanese: じゅういっぷん
    english: 11 minutes
    kanji: 十一分
    sound_file: tts/じゅういっぷん_8d706.wav
  - japanese: じゅうにふん
    english: 12 minutes
    kanji: 十二分
    sound_file: tts/じゅうにふん_15914.wav
  - japanese: じゅうさんぷん
    english: 13 minutes
    kanji: 十三分
    sound_file: tts/じゅうさんぷん_01087.wav
  - japanese: じゅうよんぷん
    english: 14 minutes
    kanji: 十四分
    sound_file: tts/じゅうよんぷん_291b2.wav
  - japanese: じゅうごふん
    english: 15 minutes
    kanji: 十五分
    sound_file: tts/じゅうごふん_96408.wav
  - japanese: じゅうろっぷん
    english: 16 minutes
    kanji: 十六分
    sound_file: tts/じゅうろっぷん_c5b95.wav
  - japanese: じゅうななふん
    english: 17 minutes
    kanji: 十七分
    sound_file: tts/じゅうななふん_45112.wav
  - japanese: じゅうはっぷん
    english: 18 minutes
    kanji: 十八分
    sound_file: tts/じゅうはっぷん_089f3.wav
  - japanese: じゅうきゅうふん
    english: 19 minutes
    kanji: 十九分
    sound_file: tts/じゅうきゅうふん_e205f.wav
  - japanese: にじゅっぷん
    english: 20 minutes
    kanji: 二十分
    sound_file: tts/にじゅっぷん_8c3bb.wav
  - japanese: さんじゅっぷん
    english: 30 minutes
    kanji: 三十分
    sound_file: tts/さんじゅっぷん_2facc.wav
