tags:
- Genki_1
- Lesson_1
- Grammar
vocabulary:
- tags:
  - Particles
  vocabulary:
  - japanese: XはY
    japanese_note: (pronounced 'wa')
    english: Topic marker (as for X, Y)
    sound_file: tts/XはY_fd55e.wav
  - japanese: Xですか？
    english: Is it X?
    sound_file: tts/Xですか？_d382e.wav
  - japanese: XのY
    english: Possessive marker (X's Y, Y of X)
    sound_file: tts/XのY_1839d.wav
