tags:
- Genki_1
- Lesson_1
- Grammar
vocabulary:
- tags:
  - Particles
  vocabulary:
  - japanese: XはY
    japanese_note: (pronounced 'wa')
    english: Topic marker (as for X, Y)
  - japanese: Xですか？
    english: Is it X?
  - japanese: XのY
    english: Possessive marker (X's Y, Y of X)
