tags:
- Genki_1
- Lesson_11
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: がいこく
    english: foreign country
    kanji: 外国
    kanji_readings:
    - 外国: がいこく
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_3.mp3
  - japanese: オーストラリア
    english: Australia
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_5.mp3
  - japanese: かわ
    english: river
    kanji: 川
    kanji_readings:
    - 川: かわ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_7.mp3
  - japanese: おんせん
    english: spa; hot spring
    kanji: 温泉
    kanji_readings:
    - 温泉: おんせん
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_9.mp3
  - japanese: つり
    english: fishing
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_12.mp3
  - japanese: みずうみ
    english: lake
    kanji: 湖
    kanji_readings:
    - 湖: みずうみ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_14.mp3
  - japanese: やま
    english: mountain
    kanji: 山
    kanji_readings:
    - 山: やま
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_16.mp3
  - japanese: キャンプ
    english: camp
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_18.mp3
  - japanese: ドライブ
    english: drive
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_20.mp3
  - japanese: じんじゃ
    english: shrine
    kanji: 神社
    kanji_readings:
    - 神社: じんじゃ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_22.mp3
  - japanese: びじゅつかん
    english: art museum
    kanji: 美術館
    kanji_readings:
    - 美術: びじゅつ
    - 館: かん
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_24.mp3
  - japanese: しゃちょう
    english: president of a company
    kanji: 社長
    kanji_readings:
    - 社長: しゃちょう
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_26.mp3
  - japanese: かしゅ
    english: singer
    kanji: 歌手
    kanji_readings:
    - 歌手: かしゅ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_28.mp3
  - japanese: ルームメイト
    english: roommate
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_30.mp3
  - japanese: ホストファミリー
    english: host family
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_32.mp3
  - japanese: しょうらい
    english: future
    kanji: 将来
    kanji_readings:
    - 将来: しょうらい
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_34.mp3
  - japanese: ゆめ
    english: dream
    kanji: 夢
    kanji_readings:
    - 夢: ゆめ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_36.mp3
  - japanese: おまつり
    english: festival
    kanji: お祭り
    kanji_readings:
    - 祭: まつ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_38.mp3
  - japanese: おしょうがつ
    english: New Year's
    kanji: お正月
    kanji_readings:
    - 正月: しょうがつ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_40.mp3
  - japanese: おかし
    english: snack; sweets
    kanji: お菓子
    kanji_readings:
    - 菓子: かし
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_42.mp3
  - japanese: ビール
    english: beer
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_45.mp3
  - japanese: おもちゃ
    english: toy
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_47.mp3
  - japanese: こんがっき
    english: this semester
    kanji: 今学期
    kanji_readings:
    - 今: こん
    - 学期: がっき
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_49.mp3
  - japanese: らいがっき
    english: next semester
    kanji: 来学期
    kanji_readings:
    - 来: らい
    - 学期: がっき
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_51.mp3
  - japanese: じゅぎょう
    english: class
    kanji: 授業
    kanji_readings:
    - 授業: じゅぎょう
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_53.mp3
  - japanese: こちら
    english: this person (polite)
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_55.mp3
- tags:
  - U-verbs
  - Verb
  vocabulary:
  - japanese: うそをつく
    english: to tell a lie
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_58.mp3
  - japanese: おなかがすく
    english: to become hungry
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_60.mp3
  - japanese: かう
    english: to own (a pet) (〜を)
    kanji: 飼う
    kanji_readings:
    - 飼: か
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_62.mp3
  - japanese: サボる
    english: to cut (classes) (〜を)
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_64.mp3
  - japanese: とる
    english: to take (a class); to get (a grade) (〜を)
    kanji: 取る
    kanji_readings:
    - 取: と
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_66.mp3
  - japanese: ならう
    english: to learn (〜を)
    kanji: 習う
    kanji_readings:
    - 習: なら
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_69.mp3
  - japanese: のぼる
    english: to climb (<i>place</i>&nbsp;に)
    kanji: 登る
    kanji_readings:
    - 登: のぼ
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_71.mp3
  - japanese: はしる
    english: to run
    kanji: 走る
    kanji_readings:
    - 走: はし
    verb_type: godan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_73.mp3
- tags:
  - Ru-verbs
  - Verb
  vocabulary:
  - japanese: つかれる
    english: to get tired
    kanji: 疲れる
    kanji_readings:
    - 疲: つか
    verb_type: ichidan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_76.mp3
  - japanese: やめる
    english: to quit (〜を)
    verb_type: ichidan
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_78.mp3
- tags:
  - Irregular_Verbs
  - Verb
  vocabulary:
  - japanese: けんかする
    english: to have a fight; to quarrel
    verb_type: irregular
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_81.mp3
  - japanese: しょうかいする
    english: to introduce (<i>person </i>に <i>person </i>を)
    kanji: 紹介する
    kanji_readings:
    - 紹介: しょうかい
    verb_type: irregular
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_84.mp3
  - japanese: ダイエットする
    english: to go on a diet
    verb_type: irregular
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_86.mp3
  - japanese: ちこくする
    english: to be late (for an appointment) (〜に)
    kanji: 遅刻する
    kanji_readings:
    - 遅刻: ちこく
    verb_type: irregular
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_88.mp3
  - japanese: りゅうがくする
    english: to study abroad (<i>place</i>&nbsp;に)
    kanji: 留学する
    kanji_readings:
    - 留学: りゅうがく
    verb_type: irregular
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_90.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: しゅっしん
    english: coming from (<i>place</i>&nbsp;の)
    kanji: 出身
    kanji_readings:
    - 出身: しゅっしん
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_93.mp3
  - japanese: ひさしぶり
    english: it has been a long time
    kanji: 久しぶり
    kanji_readings:
    - 久: ひさ
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_95.mp3
  - japanese: まあまあ
    english: okay; so-so
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_97.mp3
  - japanese: もっと
    english: more
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_100.mp3
  - japanese: あと
    english: after (an event) (<i>event</i>&nbsp;の)
    kanji: 後
    kanji_readings:
    - 後: あと
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_102.mp3
  - japanese: そして
    english: and then
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_104.mp3
  - japanese: 〜だけ
    english: just ...; only ...
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_106.mp3
  - japanese: 〜てん
    english: '... points'
    kanji: 〜点
    kanji_readings:
    - 点: てん
    sound_file: genki_1/Kaiwa_Bunpo_L11/K11_07/K11_07_109.mp3
